<?php

use yii\helpers\Html;
?>
<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html>

<head>
  <meta charset="UTF-8" />
  <title> </title>
  <meta name="author" content="SLX SLX" />
  <meta name="title" content=" " />
    <style>
    /* @page {
        margin: 4px 14px;
    } */
    * {
        font-family: Times New Roman;
        font-size: 10pt;
    }

    a.NoteRef {
        text-decoration: none;
    }

    hr {
        height: 1px;
        padding: 0;
        margin: 3px 0px;
        border: 0;
        border-top: 1px solid black;
    }

    table {
        border: 0px;
        border-spacing: 0px;
        width: 100%;
    }

    /* table  {
        width: 100%;
    }

    table, td, tr {
        border-collapse: collapse;
        border: 1px black solid;
    } */
    /* td {
        border: 1px solid black;
    } */

    .Normal {
        font-size: 12pt;
    }

    h1 {
        font-family: 'Garamond';
        font-size: 11pt;
        font-weight: bold;
    }

    h2 {
        font-family: 'Arial';
        font-size: 10pt;
        font-weight: bold;
    }

    h3 {
        font-family: 'Arial';
        font-size: 10pt;
        font-weight: bold;
    }

    .footer {
        margin-top: 0;
        margin-bottom: 0;
    }

    .page number {
        font-family: 'Times New Roman';
    }

    .header {
        margin-top: 0;
        margin-bottom: 0;
    }

    .Body Text {
        font-size: 9pt;
    }

    .Balloon Text {
        font-family: 'Tahoma';
        font-size: 8pt;
    }

    .Balloon Text Char {
        font-family: 'Tahoma';
        font-size: 8pt;
    }

    .page-break {
        page-break-after: always;
    }
    </style>
</head>

<body>
    <div class="main-content">
        <table class="TableGrid">
            <tr>
                <td style="width: 62%">
                    <?= Html::img('var:logord25', ['width' => '3cm']) ?>
                </td>
                <td style="font-size: 11px;">
                    BENGKEL CAT SOLO RD-25 AUTO BODY
                    <br>
                    9QHR+4PQ, PD. III, PONDOK, KEC. GROGOL, KABUPATEN SUKOHARJO, JAWA TENGAH 57552
                    <br>
                    TELP. 0815-7816-8823
                </td>
            </tr>
        </table>
        <hr>
        <table class="TableGrid">
            <tr>
                <td style="font-size: 14px;">
                    <center>
                        <b>PERINTAH KERJA BENGKEL</b>
                        <br>
                        <div style="font-size: 16px;">NO. <b style="font-size: 16px;"><?= $model->number ?></b></div>
                        STATUS : <?= strtoupper($model->status) ?>
                    </center>
                </td>
            </tr>
        </table>
        <hr>
        <table class="TableGrid" style="margin-left: 84px; margin-right: auto; font-size: 13px;">
            <tr>
                <td width="20%">
                    NO. POLISI
                </td>
                <td width="2%">
                    :
                </td>
                <td width="38%">
                    <?= $modelCustomer->license_plate ?>
                </td>
                <td width="22%">
                    TANGGAL MASUK
                </td>
                <td width="2%">
                    :
                </td>
                <td width="46%">
                    <?= date('d-m-Y', strtotime($model->entry_date)) ?>
                </td>
            </tr>
            <tr>
                <td width="20%">
                    MERK / TIPE
                </td>
                <td width="2%">
                    :
                </td>
                <td width="38%">
                    <?= strtoupper($modelCustomer->brand) ?> / <?= strtoupper($modelCustomer->type) ?>
                </td>
                <td width="22%">
                    TANGGAL KELUAR
                </td>
                <td width="2%">
                    :
                </td>
                <td width="46%">
                    <?= date('d-m-Y', strtotime($model->completion_date)) ?>
                </td>
            </tr>
            <tr>
                <td width="20%">
                    WARNA
                </td>
                <td width="2%">
                    :
                </td>
                <td width="38%">
                    <?= strtoupper($modelCustomer->color) ?>
                </td>
                <td width="22%">
                    NAMA CUSTOMER
                </td>
                <td width="2%">
                    :
                </td>
                <td width="46%">
                    <?= strtoupper($modelCustomer->name) ?>
                </td>
            </tr>
            <tr>
                <td width="20%">
                    TAHUN
                </td>
                <td width="2%">
                    :
                </td>
                <td width="38%">
                    <?= strtoupper($modelCustomer->year) ?>
                </td>
                <td width="22%">
                    NO. TELP
                </td>
                <td width="2%">
                    :
                </td>
                <td width="46%">
                    <?= strtoupper($modelCustomer->phone_number) ?>
                </td>
            </tr>
            <tr>
                <td width="20%">
                    NOMOR RANGKA
                </td>
                <td width="2%">
                    :
                </td>
                <td width="38%">
                    <?= strtoupper($modelCustomer->vehicle_identification_number) ?>
                </td>
                <td width="22%">
                    EMAIL
                </td>
                <td width="2%">
                    :
                </td>
                <td width="46%">
                    <?= strtoupper($modelCustomer->email) ?>
                </td>
            </tr>
            <tr>
                <td width="20%" style="vertical-align: top;">
                    NOMOR MESIN
                </td>
                <td width="2%" style="vertical-align: top;">
                    :
                </td>
                <td width="38%" style="vertical-align: top;">
                    <?= strtoupper($modelCustomer->engine_number) ?>
                </td>
                <td width="22%" style="vertical-align: top;">
                    ALAMAT
                </td>
                <td width="2%" style="vertical-align: top;">
                    :
                </td>
                <td width="46%" style="vertical-align: top;">
                    <?= strtoupper($modelCustomer->address) ?>
                </td>
            </tr>
        </table>
        <hr>
        <table class="TableGrid" style="width: 100%; margin-top: 4px;margin-left: 100px; margin-right: 80px; font-size: 12px;">
            <tr>
                <td width="100%" colspan="5">
                    <p><b>JASA PERBAIKAN</b></p>
                </td>
            </tr>
            <tr>
                <td width="5%" style="font-weight: bold">
                    NO.
                </td>
                <td width="56%" style="font-weight: bold">
                    NAMA
                </td>
                <td width="13%" style="font-weight: bold">
                    HARGA
                </td>
                <td width="13%" style="font-weight: bold">
                    DISKON
                </td>
                <td width="13%" style="font-weight: bold">
                    SUBTOTAL
                </td>
            </tr>
            <?php $i = 1; foreach($modelDetailService as $rowService): ?>
            <tr>
                <td style="text-align: left">
                    <?= $i ?>
                </td>
                <td style="text-align: left">
                    <?= strtoupper($rowService->service_name) ?>
                </td>
                <td style="text-align: right">
                    <?= number_format($rowService->manual_price, 0, ',', '.') ?>
                </td>
                <td style="text-align: right">
                    <?= $rowService->manual_discount ?>.00%
                </td>
                <td style="text-align: right">
                    <?= number_format($rowService->subtotal, 0, ',', '.') ?>
                </td>
            </tr>
            <?php $i++; endforeach; ?>
        </table>
        <br>
        <?php if (count($modelDetailSparepart) > 0): ?>
        <!-- <div class="page-break"></div> -->
        <table class="TableGrid" style="width: 100%; margin-top: 0px;margin-left: 100px; margin-right: 80px; font-size: 12px;">
            <tr>
                <td width="100%" colspan="5">
                    <p><b>SPAREPART</b></p>
                </td>
            </tr>
            <tr>
                <td width="5%" style="font-weight: bold">
                    NO.
                </td>
                <td width="56%" style="font-weight: bold">
                    NAMA
                </td>
                <td width="13%" style="font-weight: bold">
                    HARGA
                </td>
                <td width="13%" style="font-weight: bold">
                    DISKON
                </td>
                <td width="13%" style="font-weight: bold">
                    SUBTOTAL
                </td>
            </tr>
            <?php $i = 1; foreach($modelDetailSparepart as $rowSparepart): ?>
            <tr>
                <td style="text-align: left">
                    <?= $i ?>
                </td>
                <td style="text-align: left">
                    <?= strtoupper($rowSparepart->sparepart_name) ?>
                </td>
                <td style="text-align: right">
                    <?= number_format($rowSparepart->manual_price, 0, ',', '.') ?>
                </td>
                <td style="text-align: right">
                    <?= $rowSparepart->manual_discount ?>.00%
                </td>
                <td style="text-align: right">
                    <?= number_format($rowSparepart->subtotal, 0, ',', '.') ?>
                </td>
            </tr>
            <?php $i++; endforeach; ?>
        </table>
        <?php endif; ?>
        <br>
        <table class="TableGrid" style="margin-top: 0px;margin-left: 100px; margin-right: 80px; font-size: 12px;">
            <tr>
                <td colspan="4" style="text-align: right"><b>TOTAL PERBAIKAN : </b></td>
                <td style="text-align: right"><?= number_format($model->total_service, 0, ',', '.') ?></td>
            </tr>
            <?php if (count($modelDetailSparepart) > 0): ?>
            <tr>
                <td colspan="4" style="text-align: right"><b>TOTAL SPAREPART : </b></td>
                <td style="text-align: right"><?= number_format($model->total_sparepart, 0, ',', '.') ?></td>
            </tr>
            <?php endif; ?>
            <tr>
                <td colspan="4" style="text-align: right"><b>GRAND TOTAL : </b></td>
                <td style="text-align: right"><?= number_format($model->grand_total, 0, ',', '.') ?></td>
            </tr>
        </table>
        <br>
        <br>
        <table class="TableGrid" style="font-size: 12px;">
            <tr>
                <td style="text-align: center; width: 50%">
                    SERVICE ADVISOR
                </td>
                <td style="text-align: center; width: 50%">
                    PELANGGAN
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr>
                <td style="text-align: center; width: 50%; font-size: 12px;">
                    <hr style="width: 40%;margin-left: auto;margin-right: auto; margin-bottom: 3px;">
                    <?= strtoupper($modelUser->name) ?>
                </td>
                <td style="text-align: center; width: 50%; font-size: 12px;">
                    <hr style="width: 40%;margin-left: auto;margin-right: auto; margin-bottom: 3px;">
                    <?= strtoupper($modelCustomer->name) ?>
                </td>
            </tr>
        </table>
    </div>
</body>

</html>