<?php

use yii\helpers\Html;
?>
<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html>

<head>
  <meta charset="UTF-8" />
  <title> </title>
  <meta name="author" content="SLX SLX" />
  <meta name="title" content=" " />
    <style>
    /* @page {
        margin: 4px 14px;
    } */
    * {
        font-family: Times New Roman;
        font-size: 10pt;
    }

    a.NoteRef {
        text-decoration: none;
    }

    hr {
        height: 1px;
        padding: 0;
        margin: 3px 0px;
        border: 0;
        border-top: 1px solid black;
    }

    table {
        border: 0px;
        border-spacing: 0px;
        width: 100%;
    }

    /* table  {
        width: 100%;
    }

    table, td, tr {
        border-collapse: collapse;
        border: 1px black solid;
    } */
    /* td {
        border: 1px solid black;
    } */

    .Normal {
        font-size: 12pt;
    }

    h1 {
        font-family: 'Garamond';
        font-size: 11pt;
        font-weight: bold;
    }

    h2 {
        font-family: 'Arial';
        font-size: 10pt;
        font-weight: bold;
    }

    h3 {
        font-family: 'Arial';
        font-size: 10pt;
        font-weight: bold;
    }

    .footer {
        margin-top: 0;
        margin-bottom: 0;
    }

    .page number {
        font-family: 'Times New Roman';
    }

    .header {
        margin-top: 0;
        margin-bottom: 0;
    }

    .Body Text {
        font-size: 9pt;
    }

    .Balloon Text {
        font-family: 'Tahoma';
        font-size: 8pt;
    }

    .Balloon Text Char {
        font-family: 'Tahoma';
        font-size: 8pt;
    }

    .page-break {
        page-break-after: always;
    }
    </style>
</head>

<body>
    <div class="main-content">
        <table class="TableGrid" style="width: 100%; margin-top: 0px;margin-left: 100px; margin-right: 80px; font-size: 11px;">
            <tr>
                <td width="100%" colspan="5">
                    <p><b>JASA PERBAIKAN</b></p>
                </td>
            </tr>
            <tr>
                <td width="5%" style="font-weight: bold">
                    No.
                </td>
                <td width="56%" style="font-weight: bold">
                    Nama
                </td>
                <td width="13%" style="font-weight: bold">
                    Harga
                </td>
                <td width="13%" style="font-weight: bold">
                    Diskon
                </td>
                <td width="13%" style="font-weight: bold">
                    Subtotal
                </td>
            </tr>
            <?php $i = 1; foreach($modelDetailService as $rowService): ?>
            <tr>
                <td style="text-align: left">
                    <?= $i ?>
                </td>
                <td style="text-align: left">
                    <?= $rowService->service_name ?>
                </td>
                <td style="text-align: right">
                    <?= number_format($rowService->manual_price, 0, ',', '.') ?>
                </td>
                <td style="text-align: right">
                    <?= $rowService->manual_discount ?>.00%
                </td>
                <td style="text-align: right">
                    <?= number_format($rowService->subtotal, 0, ',', '.') ?>
                </td>
            </tr>
            <?php $i++; endforeach; ?>
            <tr>
                <td colspan="5">
                    <p>&nbsp;</p>
                </td>
            </tr>
        </table>
        <?php if (count($modelDetailSparepart) > 0): ?>
        <div class="page-break"></div>
        <table class="TableGrid" style="width: 100%; margin-top: 0px;margin-left: 100px; margin-right: 80px; font-size: 11px;">
            <tr>
                <td width="100%" colspan="5">
                    <p><b>JASA SPAREPART</b></p>
                </td>
            </tr>
            <tr>
                <td width="5%" style="font-weight: bold">
                    No.
                </td>
                <td width="56%" style="font-weight: bold">
                    Nama
                </td>
                <td width="13%" style="font-weight: bold">
                    Harga
                </td>
                <td width="13%" style="font-weight: bold">
                    Diskon
                </td>
                <td width="13%" style="font-weight: bold">
                    Subtotal
                </td>
            </tr>
            <?php $i = 1; foreach($modelDetailSparepart as $rowSparepart): ?>
            <tr>
                <td style="text-align: left">
                    <?= $i ?>
                </td>
                <td style="text-align: left">
                    <?= $rowSparepart->sparepart_name ?>
                </td>
                <td style="text-align: right">
                    <?= number_format($rowSparepart->manual_price, 0, ',', '.') ?>
                </td>
                <td style="text-align: right">
                    <?= $rowSparepart->manual_discount ?>.00%
                </td>
                <td style="text-align: right">
                    <?= number_format($rowSparepart->subtotal, 0, ',', '.') ?>
                </td>
            </tr>
            <?php $i++; endforeach; ?>
        </table>
        <?php endif; ?>
        <div class="page-break"></div>
        <table class="TableGrid" style="margin-top: 0px;margin-left: 100px; margin-right: 80px; font-size: 11px;">
            <tr>
                <td colspan="4" style="text-align: right"><b>TOTAL PERBAIKAN : </b></td>
                <td style="text-align: right"><?= number_format($model->total_service, 0, ',', '.') ?></td>
            </tr>
            <?php if (count($modelDetailSparepart) > 0): ?>
            <tr>
                <td colspan="4" style="text-align: right"><b>TOTAL SPAREPART : </b></td>
                <td style="text-align: right"><?= number_format($model->total_sparepart, 0, ',', '.') ?></td>
            </tr>
            <?php endif; ?>
            <tr>
                <td colspan="4" style="text-align: right"><b>GRAND TOTAL : </b></td>
                <td style="text-align: right"><?= number_format($model->grand_total, 0, ',', '.') ?></td>
            </tr>
        </table>
        <br>
        <br>
        <br>
        <table class="TableGrid" style="font-size: 11px;">
            <tr>
                <td style="text-align: center; width: 50%">
                    Service Advisor
                </td>
                <td style="text-align: center; width: 50%">
                    Pelanggan
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr>
                <td style="text-align: center; width: 50%">
                    <hr style="width: 40%;margin-left: auto;margin-right: auto; margin-bottom: 3px;">
                    <?= $modelUser->name ?>
                </td>
                <td style="text-align: center; width: 50%">
                    <hr style="width: 40%;margin-left: auto;margin-right: auto; margin-bottom: 3px;">
                    <?= $modelCustomer->name ?>
                </td>
            </tr>
        </table>
    </div>
</body>

</html>